#!/bin/sh
#derived from gphoto2

srcdir=`dirname $0`

ACLOCAL_FLAGS="-I ${srcdir}/m4 ${ACLOCAL_FLAGS}"

fail() {
    status=$?
    echo "Last command failed with status $status in directory $(pwd)."
    echo "Aborting."
    exit $status
}

echo "Cleaning stuff generated by libtoolize"
rm -f ltmain.sh config.guess config.sub

echo "Running libtoolize"
libtoolize || fail

echo "Cleaning stuff generated by aclocal"
rm -f aclocal.m4

echo "Running aclocal $ACLOCAL_FLAGS"
aclocal $ACLOCAL_FLAGS || fail

echo "Cleaning stuff generated by autoheader"
rm -f config.h.in libgphoto2/config.h.in

echo "Running autoheader"
autoheader || fail


echo "Cleaning stuff generated by automake"
rm -f depcomp install-sh missing mkinstalldirs
rm -f stamp-h*

echo "Running automake --add-missing --gnu"
automake --add-missing --gnu || fail

echo "Cleaning stuff generated by autoconf"
rm -f configure
rm -rf autom4te*.cache/

echo "Running autoconf"
autoconf ||  fail

echo "Finished!"
